### ISSUE TITLE
Any chance of getting this to work on QNAP TS-209 (Orion) device?

### ISSUE THREAD

**Issue by NorthyIE** [amouiche/qnap_mtd_resize_for_bullseye#38]
Hi,

I've got an old QNAP TS-209 that I would like to use Debian 11 on, and this device (as being the predecessor to the kirkwood devices) has the same issue with the space being to small for the newer kernels.
I am running Debian 11 with kernel 4.19 from Debian 9 successfully at the moment.
Here is my uname -a:
`Linux NAS8C3B85 4.19.0-0.bpo.19-marvell #1 Debian 4.19.232-1~deb9u1 (2022-03-08) armv5tel GNU/Linux`
Is there any chance that this script can be modified to support the orion devices as well?

here is the current layout:
```
root@NAS8C3B85:~# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00080000 00020000 "U-Boot"
mtd1: 00200000 00020000 "Kernel"
mtd2: 00400000 00020000 "RootFS1"
mtd3: 00100000 00020000 "RootFS2"
mtd4: 00020000 00020000 "U-Boot Config"
mtd5: 00060000 00020000 "NAS Config"
```

Thanks!

**Comment by amouiche** [comment]
Hello Sebastian

I just check the TS-209 specifications, and 8MB flash is definitely too
low (TS119/219/419 have16MB).

Looking at the current MTD partitionning on TS209 (another guy just ask
the same question for TS109), it looks like we can only extend the
kernel from 2048KB to 2432KB. 
Since current image is 2396 KB, you will only have few months
before 2432KB will not be sufficient.

The userfs will be limited to 5MB, which is definitely not a lot.

Despite being a great device, I would recommend to switch from TS109 to
another NAS. You can find cheap 2nd hand TSx19...

Arnaud
