### ISSUE TITLE
default loop0 risks messing up systems with other loop devices

### ISSUE THREAD

**Issue by docteurmystere** [amouiche/qnap_mtd_resize_for_bullseye#5]
suggesting the use of 'losetup -f' to select the first free loop device

**Comment by amouiche** [comment]
you are right... I miss the --show option to capture the /dev/loop found

**Comment by docteurmystere** [comment]
tried this and works.

`parser.add_argument("--loop", metavar="DEV", default=subprocess.check_output(["/sbin/losetup","-f"]).strip().decode('ascii'), help="/dev/loopX device to use for 'NAS config' FS resize (default: use the first loop available)")`

**Comment by amouiche** [comment]
Hello. I just create a "dev" branch with changes for all your issues:
- auto loop setup
- possibility to skip bootargs and bootcmd
- no absolute path for flashcp & co

I don't have the possibility to fully test since I must downgrade my QNAP test device to buster first. But can you at least check it in dryrun mode ?

**Comment by amouiche** [comment]
"losetup -f" feature is now used by the script
